# Generated by Django 2.1.7 on 2019-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
