# Generated by Django 2.1.7 on 2019-02-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0002_auto_20190221_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='lesson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alice.Lesson'),
        ),
    ]
