# Generated by Django 2.1.7 on 2019-03-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0003_auto_20190221_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alice.Group'),
        ),
    ]
