# Generated by Django 2.1.7 on 2019-03-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0004_auto_20190308_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliceUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=65)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alice.Group')),
                ('univercity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alice.Univercity')),
            ],
        ),
    ]
