# Generated by Django 2.1.7 on 2019-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0005_aliceusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='readable_name',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
        migrations.AddField(
            model_name='univercity',
            name='readable_name',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
