# Generated by Django 2.1.7 on 2019-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0010_auto_20190322_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
    ]
