# Generated by Django 2.1.7 on 2019-03-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0013_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
