# Generated by Django 2.1.7 on 2019-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0016_auto_20190322_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='repeat',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
