# Generated by Django 2.1.7 on 2019-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0017_auto_20190322_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='repeat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
