# Generated by Django 2.1.7 on 2019-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0018_auto_20190322_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='repeat',
            field=models.IntegerField(default=1),
        ),
    ]
