# Generated by Django 2.1.7 on 2019-03-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0020_auto_20190322_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
