# Generated by Django 2.1.7 on 2019-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0021_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
