# Generated by Django 2.1.7 on 2019-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0022_group_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteusers',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
